# Generated by Django 4.0.4 on 2022-06-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0003_alter_primermvt_edad_alter_primermvt_nacimiento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='primermvt',
            new_name='Familiares',
        ),
    ]
