# Generated by Django 4.0.4 on 2022-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0004_rename_primermvt_familiares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='familiares',
            options={'verbose_name': 'Familiar', 'verbose_name_plural': 'Familiares'},
        ),
    ]
