# Generated by Django 4.0.4 on 2022-06-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0005_animales_alter_familiares_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='dni',
            field=models.IntegerField(default=True, unique=True),
        ),
    ]
