# Generated by Django 4.0.4 on 2022-06-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0006_familiares_dni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animales',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animales'},
        ),
    ]
