# Generated by Django 4.0.4 on 2022-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0007_alter_animales_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('marca', models.CharField(choices=[('renault', 'Renault'), ('ford', 'Ford'), ('peugeot', 'Peugeot'), ('volkswagen', 'Volkswagen'), ('tesla', 'Tesla'), ('fiat', 'Fiat'), ('chevrolet', 'Chevrolet'), ('toyota', 'Toyota')], default=1, max_length=20)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
        migrations.AddField(
            model_name='animales',
            name='tipo',
            field=models.CharField(default='Perro', max_length=10),
        ),
    ]
