# Generated by Django 4.0.4 on 2022-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0008_vehiculos_animales_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='patente',
            field=models.CharField(default=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='animales',
            name='tipo',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10),
        ),
    ]
