# Generated by Django 4.0.4 on 2022-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0009_vehiculos_patente_alter_animales_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(choices=[('renault', 'Renault'), ('ford', 'Ford'), ('peugeot', 'Peugeot'), ('volkswagen', 'Volkswagen'), ('tesla', 'Tesla'), ('fiat', 'Fiat'), ('chevrolet', 'Chevrolet'), ('toyota', 'Toyota')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='patente',
            field=models.CharField(default='Ej: AE 123 CD ', max_length=10, unique=True),
        ),
    ]
