# Generated by Django 4.0.4 on 2022-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0010_alter_vehiculos_marca_alter_vehiculos_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animales',
            name='tipo',
            field=models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='marca',
            field=models.CharField(choices=[('Renault', 'Renault'), ('Ford', 'Ford'), ('Peugeot', 'Peugeot'), ('Volkswagen', 'Volkswagen'), ('Tesla', 'Tesla'), ('Fiat', 'Fiat'), ('Chevrolet', 'Chevrolet'), ('Toyota', 'Toyota')], max_length=20),
        ),
    ]
