# Generated by Django 4.0.4 on 2022-07-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0011_alter_animales_tipo_alter_vehiculos_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='familiares'),
        ),
    ]
