# Generated by Django 4.0.4 on 2022-07-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primermvt', '0012_familiares_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animales',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas'),
        ),
        migrations.AddField(
            model_name='vehiculos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos'),
        ),
    ]
